# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    dropbox_client:
        class: Dropbox\Client
        arguments:
            - "apitoken"
            - "logindropbox"
            
    user.provider:
        class: AppBundle\Security\FOSUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebookId}]
        
    validator.pesel:
        class: AppBundle\Validator\Constraints\PeselValidator
        tags:
            - { name: validator.constraint_validator, alias: validator_pesel }
            
    locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
            
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: [@doctrine.orm.entity_manager]

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        
